### ISSUE TITLE
Please add link in the About (for this repo)

### ISSUE THREAD

**Issue by Maar-io** [yaymalaga/magink-dapp#1]
https://yaymalaga.github.io/magink-dapp/

**Comment by yaymalaga** [comment]
The link in the README now points to my deployed frontend -> https://github.com/yaymalaga/magink-dapp/commit/ed52a74d043e3076e84f0a50d57036e03f59ea4a

**Comment by Maar-io** [comment]
For completeness, add the link to the About section. Just like the issue says. You want users to easily run the front end.

<img width="688" alt="Screenshot 2023-09-11 at 09 52 09" src="https://github.com/yaymalaga/magink-dapp/assets/34627453/63cb0166-5720-4f2e-ae6e-2b2d45ed411d">
