### ISSUE TITLE
How do I know the NFT is minted? Where can I see the NFT?

### ISSUE THREAD

**Issue by Maar-io** [yaymalaga/magink-dapp#2]
I need to verify the minted NFT and I want to see how you did it with IPFS

**Comment by yaymalaga** [comment]
The Magink contract now relies on the Wizard contract for the next_id to use ("get_next_id") and to check if an user has already minted the token ("get_is_already_minted"). Moreover, I have exposed the metadata of the token so it can be used on the frontend ("get_token_image"). Now, after minting the token, its image metadata will be retrieved and the image is shown using the IPFS link!! ->  https://github.com/yaymalaga/magink-dapp/commit/ed52a74d043e3076e84f0a50d57036e03f59ea4a

**Comment by Maar-io** [comment]
In general, please do not close issues until the other side (in this case me) approves that issues is resolved
