### ISSUE TITLE
e2e test discussion

### ISSUE THREAD

**Issue by Maar-io** [yaymalaga/magink-dapp#4]
Did you compare your e2e test with manic minter example?

https://github.com/swankyhub/manic-minter/blob/86684e3d55115f72de02abb1578afd552522ed6e/manicminter/lib.rs#L179

**Comment by yaymalaga** [comment]
E2e tests are now working fine!! ->  https://github.com/yaymalaga/magink-dapp/commit/ed52a74d043e3076e84f0a50d57036e03f59ea4a
